feat: TypeSafeHTTPBasic
IBM-Swift/Kitura-CredentialsHTTP pull request #49
Opened 2018-06-01 08:27 UTC by Andrew-Lees11

Once [typeSafeCredentials](https://github.com/IBM-Swift/Kitura-Credentials/pull/64) is merged we can implement HTTP basic auth using typeSafeMiddlware. 

Docs description:
A `TypeSafeCredentials` plugin for HTTP basic authentication. This protocol will be implemented by a Swift object defined by the user. The plugin must implement a `verifyPassword` function which takes a username and password as input and returns an instance of `Self` on success or `nil` on failure. This instance must contain the authentication `provider` (defaults to "HTTPBasic") and an `id`, uniquely identifying the user. The users object can then be used in TypeSafeMiddlware routes to authenticate with HTTP basic.

2018-06-01 08:33 UTC, Andrew-Lees11 commented
I have removed inProgress from authenticate since in current credentials it will never be invoked. This will make it different from credentials authenticate signature so i was unsure if we want to maintain consistency?

2018-06-01 08:34 UTC, Andrew-Lees11 commented
The tests are currently failing since they require typeSafeMiddleware which will only be available in Kitura 2.4.

2018-06-01 15:21 UTC, ianpartridge commented on README.md
> +    public static let users = ["John" : "12345", "Mary" : "qwerasdf"]
Probably make this private!

2018-06-01 16:09 UTC, djones6 commented
@Andrew-Lees11 FYI, Kitura and Credentials dependencies are merged and tagged - I have restarted the CI.

2018-06-04 10:25 UTC, ianpartridge requested changes

2018-06-04 10:25 UTC, ianpartridge commented on Tests/CredentialsHTTPTests/TestTypeSafeBasic.swift
> +            ("testTypeSafeNoCredentials", testTypeSafeNoCredentials),
This array is missing some of the tests!

2018-06-04 10:25 UTC, ianpartridge commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +        else {
Please put the else on the previous line.

2018-06-04 10:25 UTC, ianpartridge commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +            else {
Same comment.

2018-06-04 10:25 UTC, ianpartridge commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +                onFailure(.badRequest, nil)
`return onFailure...`

2018-06-04 10:25 UTC, ianpartridge commented on Tests/CredentialsHTTPTests/TestTypeSafeBasic.swift
> +                catch{
Merge with previous line.

2018-06-04 10:25 UTC, ianpartridge commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +    static var verifyPassword: ((String, String, @escaping (Self?) -> Void) -> Void) { get }
This isn't very type-safe, did you consider replacing these Strings with something protocol-based?

2018-06-04 13:21 UTC, djones6 commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +    static var verifyPassword: ((String, String, @escaping (Self?) -> Void) -> Void) { get }
I think we should replace with something like
```swift
static func verifyPassword(username: String, password, String, callback: @escaping (Self?) -> Void) -> Void
```
Xcode will auto-complete this much nicer than the version where we define a closure signature, and apply the labels which indicates how to handle each argument.

2018-06-04 13:24 UTC, djones6 requested changes

2018-06-04 13:24 UTC, djones6 commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +    public static var verifyPassword: ((String, String, @escaping (MyHTTPBasic?) -> Void) -> Void) =
Usage example needs updating now that this is a function

2018-06-04 13:24 UTC, djones6 commented on Sources/CredentialsHTTP/TypeSafeHTTPBasic.swift
> +    /// The closure which takes a username and password and returns a TypeSafeHTTPBasic instance on success or nil on failure.
Comment needs updating now that this is a function

2018-06-04 13:46 UTC, Andrew-Lees11 commented on Tests/CredentialsHTTPTests/TestTypeSafeBasic.swift
> +            ("testTypeSafeNoCredentials", testTypeSafeNoCredentials),
Tests have been added and this file has been added to linux main

2018-06-04 16:03 UTC, djones6 approved these changes

2018-06-05 11:42 UTC, ianpartridge approved these changes

2018-06-05 11:43 UTC, merged